[project]
main_target = "main"
build_types = ["Debug", "Release"]
default_build_type = "Debug"

[[project.targets.executable]]
name = "main"

[[project.targets.executable]]
name = "tests"
is_test = true

[[project.targets.library]]
name = "core"

[[project.targets.library]]
name = "utils"
